apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 1Gi  # Defines the size of the persistent volume
  accessModes:
    - ReadWriteOnce  # Defines that the volume can be mounted by only one node at a time
  persistentVolumeReclaimPolicy: Retain  # Retain the volume after the PVC is deleted (other options: Delete, Recycle)
  storageClassName: manual  # Define a storage class (optional)
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/nginx  # Path on the host machine (for testing purposes)
